/* Generated by Together */

package Server;

public class Servertest {
    public static void main(String[] args){
     Server tmpServer = new Server();
     tmpServer.startServer();
    }

}
