/* Generated by Together */

package Util.Commands;
import Server.User;
import Server.AdminClientServant;

public class AddUserCommand implements Command{
    private User user;
    public AddUserCommand(User paramUser){
     this.user=paramUser;
    }
    public void execute(Object target) {
    if (target instanceof AdminClientServant) {
      ((AdminClientServant) target).addUser(this.user);
    } // XXX: else Exception auslösen?
  }


}
