/* Generated by Together */

package Util.Commands;

import java.util.Vector;
import Server.AdminClientServant;

public class AddUserCommand implements Command {
    public AddUserCommand(String paramName, boolean paramIsAdmin, Vector paramAllowedChannelNames) {
        this.name = paramName;
        this.isAdmin = paramIsAdmin;
        this.allowedChannelNames = paramAllowedChannelNames;
    }

    private String name;
    private boolean isAdmin = false;
    private Vector allowedChannelNames;

    public void execute(Object target) {
        if (target instanceof AdminClientServant) {
            ((AdminClientServant)target).addUser(name, isAdmin, allowedChannelNames);
        }
    }
}
