/* Generated by Together */

package Util.Commands;

import java.util.Vector;
import Server.AdminClientServant;

/**
 * Wird von einem AdminClient erzeugt,
 * Ändert einen bestehenden User und
 * ruft editUser beim AdminClientServant auf.
 */

public class EditUserCommand implements Command {

    /**Setzt die Attribute.*/
    public EditUserCommand(String paramOldName, String paramName, String paramPassword,boolean paramIsAdmin, Vector paramAllowedChannelNames) {
        this.oldName=paramOldName;
        this.name = paramName;
        this.password=paramPassword;
        this.isAdmin = paramIsAdmin;
        this.allowedChannelNames = paramAllowedChannelNames;
    }
    /**Der alte Name des Users.*/
    private String oldName;

    /**Name des Users.*/
    private String name;

    /**Passwort des Users.*/
    private String password;

    /**Admin-Status des Users.*/
    private boolean isAdmin = false;

    /**Liste der Namen der Channels, die der Benutzer betreten darf.*/
    private Vector allowedChannelNames;

    /**Führt adminClientServant.editUser() mit den Attributen des Commands aus.*/
    public void execute(Object target) {
        if (target instanceof AdminClientServant) {
            ((AdminClientServant)target).editUser(oldName, name, password, isAdmin, allowedChannelNames);
        }
    }
}
