/* Generated by Together */

package Util.Commands;
import Client.Client;

public class LoginErrorCommand implements Command{
    public LoginErrorCommand(String errMsg){
     this.msg=errMsg;
    }

    private String msg;

     public void execute(Object target) {
    if (target instanceof Client) {
      ((Client) target).loginError(msg);
    } // XXX: else Exception auslösen?
  }

}
