/* Generated by Together */

package Util.Commands;

import Client.Client;

public class SendMsgToUserErrorCommand implements Command {

    public void execute(Object target) {
        if (target instanceof Client) {
            ((Client)target).sendMsgToUserError();
        } // XXX: else Exception auslösen?
    }
}
