/*
 * ChannelAdminGUI.java
 *
 * Created on May 24, 2001, 9:32 PM
 */

package gui;

import Client.*;

/**
 * @author  andreas
 * @version
 */
public class ChannelAdminGUI extends java.awt.Frame {

    private gui.ChatGui chatGui;

    /** Konstruktor */
    public ChannelAdminGUI(gui.ChatGui paramChatGui) {
        this.chatGui=paramChatGui;
        initComponents();
        pack();
    }

    /**
     * This method is called from within the init() method to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the FormEditor.
     */
    private void initComponents() { //GEN-BEGIN:initComponents
        channelNameLabel = new java.awt.Label();
        channelName = new java.awt.TextField();
        channelListLabel = new java.awt.Label();
        channelList = new java.awt.List();
        editChannel = new java.awt.Button();
        newChannel = new java.awt.Button();
        copyChannel = new java.awt.Button();
        saveChannel = new java.awt.Button();
        deleteChannel = new java.awt.Button();
        passiveUsersLabel = new java.awt.Label();
        passiveUsers = new java.awt.List();
        addToChannel = new java.awt.Button();
        removeFromChannel = new java.awt.Button();
        activeUsersLabel = new java.awt.Label();
        activeUsers = new java.awt.List();
        allowedForGuests = new java.awt.Checkbox();
        setLayout(
            new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        channelNameLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        channelNameLabel.setName("channelNameLabel");
        channelNameLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        channelNameLabel.setForeground(java.awt.Color.black);
        channelNameLabel.setText("Channelname");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 15);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        add(channelNameLabel, gridBagConstraints1);
        channelName.setBackground(java.awt.Color.white);
        channelName.setName("channelNameField");
        channelName.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        channelName.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        add(channelName, gridBagConstraints1);
        channelListLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        channelListLabel.setName("channelListLabel");
        channelListLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        channelListLabel.setForeground(java.awt.Color.black);
        channelListLabel.setText("Channelliste");
        channelListLabel.setAlignment(java.awt.Label.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.gridwidth = 12;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 10);
        add(channelListLabel, gridBagConstraints1);
        channelList.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        channelList.setName("channelList");
        channelList.setBackground(java.awt.Color.white);
        channelList.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 12;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 10);
        gridBagConstraints1.weightx = 1.0;
        add(channelList, gridBagConstraints1);
        editChannel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        editChannel.setLabel("Bearbeiten");
        editChannel.setName("editChannelButton");
        editChannel.setBackground(
            new java.awt.Color(204, 204, 204));
        editChannel.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 15, 0);
        gridBagConstraints1.weightx = 1.0;
        add(editChannel, gridBagConstraints1);
        newChannel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        newChannel.setLabel("Neu");
        newChannel.setName("newChannelButton");
        newChannel.setBackground(
            new java.awt.Color(204, 204, 204));
        newChannel.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 6;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 10, 15, 0);
        gridBagConstraints1.weightx = 1.0;
        add(newChannel, gridBagConstraints1);
        copyChannel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        copyChannel.setLabel("Kopieren");
        copyChannel.setName("copyChannelButton");
        copyChannel.setBackground(
            new java.awt.Color(204, 204, 204));
        copyChannel.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 15, 0);
        gridBagConstraints1.weightx = 1.0;
        add(copyChannel, gridBagConstraints1);
        saveChannel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        saveChannel.setLabel("Speichern");
        saveChannel.setName("saveChannelButton");
        saveChannel.setBackground(
            new java.awt.Color(204, 204, 204));
        saveChannel.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 6;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 6;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 0, 15, 10);
        gridBagConstraints1.weightx = 1.0;
        add(saveChannel, gridBagConstraints1);
        deleteChannel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        deleteChannel.setLabel("L\u00f6schen");
        deleteChannel.setName("deleteChannelButton");
        deleteChannel.setBackground(
            new java.awt.Color(204, 204, 204));
        deleteChannel.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 8;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 15, 10);
        gridBagConstraints1.weightx = 1.0;
        add(deleteChannel, gridBagConstraints1);
        passiveUsersLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        passiveUsersLabel.setName("passiveUsersLabel");
        passiveUsersLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        passiveUsersLabel.setForeground(java.awt.Color.black);
        passiveUsersLabel.setText("Nicht berechtigte User");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(15, 10, 0, 0);
        add(passiveUsersLabel, gridBagConstraints1);
        passiveUsers.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        passiveUsers.setMultipleMode(true);
        passiveUsers.setName("passiveUsersList");
        passiveUsers.setBackground(java.awt.Color.white);
        passiveUsers.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.gridheight = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 10, 0);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(passiveUsers, gridBagConstraints1);
        addToChannel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        addToChannel.setLabel(">>>");
        addToChannel.setName("addToChannelButton");
        addToChannel.setBackground(
            new java.awt.Color(204, 204, 204));
        addToChannel.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 5;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 2;
        gridBagConstraints1.insets = new java.awt.Insets(10, 15, 10, 15);
        add(addToChannel, gridBagConstraints1);
        removeFromChannel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        removeFromChannel.setLabel("<<<");
        removeFromChannel.setName("removeFromChannelButton");
        removeFromChannel.setBackground(
            new java.awt.Color(204, 204, 204));
        removeFromChannel.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 5;
        gridBagConstraints1.gridy = 8;
        gridBagConstraints1.gridwidth = 2;
        gridBagConstraints1.insets = new java.awt.Insets(10, 15, 10, 15);
        add(removeFromChannel, gridBagConstraints1);
        activeUsersLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        activeUsersLabel.setName("activeUsersLabel");
        activeUsersLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        activeUsersLabel.setForeground(java.awt.Color.black);
        activeUsersLabel.setText("Berechtigte User");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(15, 0, 0, 10);
        add(activeUsersLabel, gridBagConstraints1);
        activeUsers.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        activeUsers.setMultipleMode(true);
        activeUsers.setName("activeUsersList");
        activeUsers.setBackground(java.awt.Color.white);
        activeUsers.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.gridheight = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 10, 10);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(activeUsers, gridBagConstraints1);
        allowedForGuests.setBackground(
            new java.awt.Color(204, 204, 204));
        allowedForGuests.setName("allowedForGuests");
        allowedForGuests.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        allowedForGuests.setForeground(java.awt.Color.black);
        allowedForGuests.setLabel("\u00f6ffentlich");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        add(allowedForGuests, gridBagConstraints1);
    } //GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label channelNameLabel;
    private java.awt.TextField channelName;
    private java.awt.Label channelListLabel;
    private java.awt.List channelList;
    private java.awt.Button editChannel;
    private java.awt.Button newChannel;
    private java.awt.Button copyChannel;
    private java.awt.Button saveChannel;
    private java.awt.Button deleteChannel;
    private java.awt.Label passiveUsersLabel;
    private java.awt.List passiveUsers;
    private java.awt.Button addToChannel;
    private java.awt.Button removeFromChannel;
    private java.awt.Label activeUsersLabel;
    private java.awt.List activeUsers;
    private java.awt.Checkbox allowedForGuests;
    // End of variables declaration//GEN-END:variables
}
