/*
 * LogText.java
 *
 * Created on 12. Juni 2001, 16:01
 */

package gui;

import Util.Debug.*;

/**
 * @author
 * @version
 */
public class LogText extends java.awt.Frame {
    /** Creates new form LogText */
    public LogText() {
        initComponents();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the FormEditor.
     */
    private void initComponents() {
        logTextArea = new java.awt.TextArea();
        setLayout(
            new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        addWindowListener(
            new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    exitForm(evt);
                }
            });
        logTextArea.setBackground(java.awt.Color.white);
        logTextArea.setName("logTextArea");
        logTextArea.setEditable(false);
        logTextArea.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        logTextArea.setColumns(70);
        logTextArea.setForeground(java.awt.Color.black);
        logTextArea.setRows(30);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        add(logTextArea, gridBagConstraints1);
    }

    /** Schlieﬂen des Applikationsframes */
    private void exitForm(java.awt.event.WindowEvent evt) {
        this.setVisible(false);
    }

    // Variables declaration - do not modify
    java.awt.TextArea logTextArea;
    // End of variables declaration
}
