/*
 * UserAdminGUI.java
 *
 * Created on May 24, 2001, 1:44 PM
 */

package gui;

import Client.*;

/**
 * @author  andreas
 * @version
 */
public class UserAdminGUI extends java.awt.Frame {
    gui.ChatGui chatGui;

    /** Konstruktor */
    public UserAdminGUI(gui.ChatGui paramChatGui) {
        this.chatGui = paramChatGui;
        initComponents();
        addWindowListener(
            new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    exitForm(evt);
                }
            });
        pack();
    }

    /**
     * This method is called from within the init() method to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the FormEditor.
     */
    private void initComponents() { //GEN-BEGIN:initComponents
        passwordLabel = new java.awt.Label();
        loginName = new java.awt.TextField();
        passwordVerifyLabel = new java.awt.Label();
        loginNameLabel = new java.awt.Label();
        userList = new java.awt.List();
        password = new java.awt.TextField();
        passwordVerify = new java.awt.TextField();
        isAdmin = new java.awt.Checkbox();
        userListLabel = new java.awt.Label();
        passiveChannels = new java.awt.List();
        addToActive = new java.awt.Button();
        removeFromActive = new java.awt.Button();
        activeChannels = new java.awt.List();
        passiveChannelsLabel = new java.awt.Label();
        activeChannelsLabel = new java.awt.Label();
        editUser = new java.awt.Button();
        copyUser = new java.awt.Button();
        newUser = new java.awt.Button();
        saveUser = new java.awt.Button();
        deleteUser = new java.awt.Button();
        setLayout(
            new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        passwordLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        passwordLabel.setName("passwordLabel");
        passwordLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        passwordLabel.setForeground(java.awt.Color.black);
        passwordLabel.setText("Passwort");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = 3;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        add(passwordLabel, gridBagConstraints1);
        loginName.setBackground(java.awt.Color.white);
        loginName.setName("loginField");
        loginName.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        loginName.setForeground(java.awt.Color.black);
        loginName.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textField1ActionPerformed(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(loginName, gridBagConstraints1);
        passwordVerifyLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        passwordVerifyLabel.setName("passwordVerifyLabel");
        passwordVerifyLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        passwordVerifyLabel.setForeground(java.awt.Color.black);
        passwordVerifyLabel.setText("Wiederholung");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = 3;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        add(passwordVerifyLabel, gridBagConstraints1);
        loginNameLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        loginNameLabel.setName("loginLabel");
        loginNameLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        loginNameLabel.setForeground(java.awt.Color.black);
        loginNameLabel.setText("Login Name");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 3;
        gridBagConstraints1.insets = new java.awt.Insets(1, 0, 0, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        add(loginNameLabel, gridBagConstraints1);
        userList.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        userList.setName("userList");
        userList.setBackground(java.awt.Color.white);
        userList.setForeground(java.awt.Color.black);
        userList.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    list1ActionPerformed(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.gridheight = 10;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.ipadx = 3;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 30);
        gridBagConstraints1.weightx = 0.5;
        gridBagConstraints1.weighty = 1.0;
        add(userList, gridBagConstraints1);
        password.setBackground(java.awt.Color.white);
        password.setName("passwordField");
        password.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        password.setEchoChar('*');
        password.setForeground(java.awt.Color.black);
        password.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    passwordActionPerformed(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(password, gridBagConstraints1);
        passwordVerify.setBackground(java.awt.Color.white);
        passwordVerify.setName("passwordVerifyField");
        passwordVerify.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        passwordVerify.setEchoChar('*');
        passwordVerify.setForeground(java.awt.Color.black);
        passwordVerify.addActionListener(
            new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textField4ActionPerformed(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(passwordVerify, gridBagConstraints1);
        isAdmin.setBackground(
            new java.awt.Color(204, 204, 204));
        isAdmin.setName("isAdminCheckbox");
        isAdmin.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        isAdmin.setForeground(java.awt.Color.black);
        isAdmin.setLabel(" ist Admin");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        add(isAdmin, gridBagConstraints1);
        userListLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        userListLabel.setName("userListLabel");
        userListLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        userListLabel.setForeground(java.awt.Color.black);
        userListLabel.setText("Userliste");
        userListLabel.setAlignment(java.awt.Label.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 30);
        add(userListLabel, gridBagConstraints1);
        passiveChannels.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        passiveChannels.setMultipleMode(true);
        passiveChannels.setName("passiveChannelList");
        passiveChannels.setBackground(java.awt.Color.white);
        passiveChannels.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.gridheight = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 10, 15);
        gridBagConstraints1.weightx = 1.0;
        add(passiveChannels, gridBagConstraints1);
        addToActive.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        addToActive.setLabel(">>>");
        addToActive.setName("addToChannels");
        addToActive.setBackground(
            new java.awt.Color(204, 204, 204));
        addToActive.setForeground(java.awt.Color.black);
        addToActive.addMouseListener(
            new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    addToActiveMouseClicked(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 9;
        gridBagConstraints1.gridy = 9;
        add(addToActive, gridBagConstraints1);
        removeFromActive.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        removeFromActive.setLabel("<<<");
        removeFromActive.setName("removeFromChannels");
        removeFromActive.setBackground(
            new java.awt.Color(204, 204, 204));
        removeFromActive.setForeground(java.awt.Color.black);
        removeFromActive.addMouseListener(
            new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    removeFromActiveMouseClicked(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 9;
        gridBagConstraints1.gridy = 11;
        add(removeFromActive, gridBagConstraints1);
        activeChannels.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        activeChannels.setMultipleMode(true);
        activeChannels.setName("activeChannelList");
        activeChannels.setBackground(java.awt.Color.white);
        activeChannels.setForeground(java.awt.Color.black);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 10;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.gridheight = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(0, 15, 10, 10);
        gridBagConstraints1.weightx = 1.0;
        add(activeChannels, gridBagConstraints1);
        passiveChannelsLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        passiveChannelsLabel.setName("passiveChannelListField");
        passiveChannelsLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        passiveChannelsLabel.setForeground(java.awt.Color.black);
        passiveChannelsLabel.setText("Inaktive Channels");
        passiveChannelsLabel.setAlignment(java.awt.Label.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.insets = new java.awt.Insets(15, 0, 0, 10);
        add(passiveChannelsLabel, gridBagConstraints1);
        activeChannelsLabel.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        activeChannelsLabel.setName("activeChannelListField");
        activeChannelsLabel.setBackground(
            new java.awt.Color(204, 204, 204));
        activeChannelsLabel.setForeground(java.awt.Color.black);
        activeChannelsLabel.setText("Aktive Channels");
        activeChannelsLabel.setAlignment(java.awt.Label.CENTER);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 10;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.insets = new java.awt.Insets(15, 0, 0, 10);
        add(activeChannelsLabel, gridBagConstraints1);
        editUser.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        editUser.setLabel("Bearbeiten");
        editUser.setName("editUser");
        editUser.setBackground(
            new java.awt.Color(204, 204, 204));
        editUser.setForeground(java.awt.Color.black);
        editUser.addMouseListener(
            new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    editUserMouseClicked(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 12;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 30);
        add(editUser, gridBagConstraints1);
        copyUser.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        copyUser.setLabel("Kopieren");
        copyUser.setName("copyUserData");
        copyUser.setBackground(
            new java.awt.Color(204, 204, 204));
        copyUser.setForeground(java.awt.Color.black);
        copyUser.addMouseListener(
            new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    copyUserMouseClicked(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 13;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 30);
        add(copyUser, gridBagConstraints1);
        newUser.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        newUser.setLabel("Neu");
        newUser.setName("newUser");
        newUser.setBackground(
            new java.awt.Color(204, 204, 204));
        newUser.setForeground(java.awt.Color.black);
        newUser.addMouseListener(
            new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    newUserMouseClicked(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 7;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 10, 15, 0);
        gridBagConstraints1.weightx = 1.0;
        add(newUser, gridBagConstraints1);
        saveUser.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        saveUser.setLabel("Speichern");
        saveUser.setName("saveUser");
        saveUser.setBackground(
            new java.awt.Color(204, 204, 204));
        saveUser.setForeground(java.awt.Color.black);
        saveUser.addMouseListener(
            new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    saveUserMouseClicked(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 8;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 7;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 0, 15, 10);
        gridBagConstraints1.weightx = 1.0;
        add(saveUser, gridBagConstraints1);
        deleteUser.setFont(
            new java.awt.Font("SansSerif", 0, 11));
        deleteUser.setLabel("L\u00f6schen");
        deleteUser.setName("deleteUser");
        deleteUser.setBackground(
            new java.awt.Color(204, 204, 204));
        deleteUser.setForeground(java.awt.Color.black);
        deleteUser.addMouseListener(
            new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    deleteUserMouseClicked(evt);
                }
            });
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 14;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 10, 30);
        gridBagConstraints1.weightx = 1.0;
        add(deleteUser, gridBagConstraints1);
    } //GEN-END:initComponents

    private void deleteUserMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_deleteUserMouseClicked
        // Add your handling code here:
    } //GEN-LAST:event_deleteUserMouseClicked

    private void copyUserMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_copyUserMouseClicked
        // Add your handling code here:
    } //GEN-LAST:event_copyUserMouseClicked

    private void editUserMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_editUserMouseClicked
        String name = this.userList.getSelectedItem();
        this.chatGui.adminClient.getUserData(name);
    } //GEN-LAST:event_editUserMouseClicked

    private void removeFromActiveMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_removeFromActiveMouseClicked
        // Add your handling code here:
    } //GEN-LAST:event_removeFromActiveMouseClicked

    private void addToActiveMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_addToActiveMouseClicked
        // Add your handling code here:
    } //GEN-LAST:event_addToActiveMouseClicked

    private void saveUserMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_saveUserMouseClicked
        // Add your handling code here:
    } //GEN-LAST:event_saveUserMouseClicked

    private void newUserMouseClicked(java.awt.event.MouseEvent evt) { //GEN-FIRST:event_newUserMouseClicked
        // Add your handling code here:
    } //GEN-LAST:event_newUserMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_passwordActionPerformed
        // Add your handling code here:
    } //GEN-LAST:event_passwordActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_list1ActionPerformed
        // Add your handling code here:
    } //GEN-LAST:event_list1ActionPerformed

    private void textField4ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_textField4ActionPerformed
        // Add your handling code here:
    } //GEN-LAST:event_textField4ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_textField1ActionPerformed
        // Add your handling code here:
    } //GEN-LAST:event_textField1ActionPerformed

    /** Schließen des Applikationsframes */
    private void exitForm(java.awt.event.WindowEvent evt) {
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    java.awt.Label passwordLabel;
    java.awt.TextField loginName;
    java.awt.Label passwordVerifyLabel;
    java.awt.Label loginNameLabel;
    java.awt.List userList;
    java.awt.TextField password;
    java.awt.TextField passwordVerify;
    java.awt.Checkbox isAdmin;
    java.awt.Label userListLabel;
    java.awt.List passiveChannels;
    java.awt.Button addToActive;
    java.awt.Button removeFromActive;
    java.awt.List activeChannels;
    java.awt.Label passiveChannelsLabel;
    java.awt.Label activeChannelsLabel;
    java.awt.Button editUser;
    java.awt.Button copyUser;
    java.awt.Button newUser;
    java.awt.Button saveUser;
    java.awt.Button deleteUser;
    // End of variables declaration//GEN-END:variables
}
