/*
 * Applet.java
 *
 * Created on 20. Mai 2001, 23:44
 */


/**
 *
 * @author  mellon collie
 * @version 
 */
 
 import Client.*;
public class Applet extends java.applet.Applet {

    /** Initializes the applet Applet */
    public void init () {
        initComponents ();
	client=new Client();
	client.startClient();
	
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        button3 = new java.awt.Button();
        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        panel3 = new java.awt.Panel();
        textArea1 = new java.awt.TextArea();
        panel5 = new java.awt.Panel();
        button5 = new java.awt.Button();
        textField2 = new java.awt.TextField();
        setLayout(new java.awt.BorderLayout());
        
        panel1.setLayout(card);
        panel1.setFont(new java.awt.Font ("Dialog", 0, 11));
        panel1.setName("panel2");
        panel1.setBackground(new java.awt.Color (204, 204, 204));
        panel1.setForeground(java.awt.Color.black);
        
        panel2.setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints1;
          panel2.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel2.setName("panel3");
          panel2.setBackground(new java.awt.Color (153, 153, 153));
          panel2.setForeground(java.awt.Color.black);
          
          button3.setFont(new java.awt.Font ("Dialog", 0, 11));
            button3.setLabel("login als Gast");
            button3.setName("button3");
            button3.setBackground(java.awt.Color.lightGray);
            button3.setForeground(java.awt.Color.black);
            button3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    button3MousePressed(evt);
                }
            }
            );
            gridBagConstraints1 = new java.awt.GridBagConstraints();
            gridBagConstraints1.gridx = 2;
            gridBagConstraints1.gridy = 0;
            panel2.add(button3, gridBagConstraints1);
            
            
          textField1.setBackground(java.awt.Color.white);
            textField1.setName("textfield1");
            textField1.setFont(new java.awt.Font ("Dialog", 0, 11));
            textField1.setColumns(30);
            textField1.setForeground(java.awt.Color.black);
            gridBagConstraints1 = new java.awt.GridBagConstraints();
            gridBagConstraints1.gridx = 1;
            gridBagConstraints1.gridy = 0;
            panel2.add(textField1, gridBagConstraints1);
            
            
          label1.setFont(new java.awt.Font ("Dialog", 0, 11));
            label1.setName("label1");
            label1.setBackground(new java.awt.Color (153, 153, 153));
            label1.setForeground(java.awt.Color.black);
            label1.setText("Gastname:");
            gridBagConstraints1 = new java.awt.GridBagConstraints();
            gridBagConstraints1.gridx = 0;
            gridBagConstraints1.gridy = 0;
            panel2.add(label1, gridBagConstraints1);
            
            panel1.add(panel2, "card1");
          
          
        panel3.setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints2;
          panel3.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel3.setName("panel4");
          panel3.setBackground(new java.awt.Color (153, 153, 153));
          panel3.setForeground(java.awt.Color.black);
          
          textArea1.setBackground(java.awt.Color.white);
            textArea1.setName("text1");
            textArea1.setFont(new java.awt.Font ("Dialog", 0, 11));
            textArea1.setForeground(java.awt.Color.black);
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            panel3.add(textArea1, gridBagConstraints2);
            
            
          panel5.setLayout(new java.awt.GridBagLayout());
            java.awt.GridBagConstraints gridBagConstraints4;
            panel5.setFont(new java.awt.Font ("Dialog", 0, 11));
            panel5.setName("panel6");
            panel5.setBackground(new java.awt.Color (153, 153, 153));
            panel5.setForeground(java.awt.Color.black);
            
            button5.setFont(new java.awt.Font ("Dialog", 0, 11));
              button5.setLabel("sende Nachricht");
              button5.setName("button5");
              button5.setBackground(java.awt.Color.lightGray);
              button5.setForeground(java.awt.Color.black);
              button5.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                      button5MousePressed(evt);
                  }
              }
              );
              gridBagConstraints4 = new java.awt.GridBagConstraints();
              gridBagConstraints4.gridx = 0;
              gridBagConstraints4.gridy = 0;
              panel5.add(button5, gridBagConstraints4);
              
              
            textField2.setBackground(java.awt.Color.white);
              textField2.setName("textfield2");
              textField2.setFont(new java.awt.Font ("Dialog", 0, 11));
              textField2.setColumns(30);
              textField2.setForeground(java.awt.Color.black);
              gridBagConstraints4 = new java.awt.GridBagConstraints();
              panel5.add(textField2, gridBagConstraints4);
              
              gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 0;
            gridBagConstraints2.gridy = 1;
            panel3.add(panel5, gridBagConstraints2);
            
            panel1.add(panel3, "card2");
          
          
        add(panel1, java.awt.BorderLayout.CENTER);
	
	
	
        
    }//GEN-END:initComponents

  private void button5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MousePressed
// Add your handling code here:

   client.sendMsgToChannel(textField2.getText());
   textField2.setText("");
	textArea1.setText(client.channelMsgBuffer);
	textArea1.setCaretPosition(client.channelMsgBuffer.length());

  }//GEN-LAST:event_button5MousePressed

  private void button3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MousePressed
// Add your handling code here:
   client.loginAsGuest(textField1.getText());
   client.joinChannel("Virtuelle Konferenz");
   card.next(panel1);
   
   
  }//GEN-LAST:event_button3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Button button3;
    private java.awt.TextField textField1;
    private java.awt.Label label1;
    private java.awt.Panel panel3;
    private java.awt.TextArea textArea1;
    private java.awt.Panel panel5;
    private java.awt.Button button5;
    private java.awt.TextField textField2;
        private java.awt.CardLayout card = new java.awt.CardLayout();
    private Client client;

    // End of variables declaration//GEN-END:variables

}
