/*
 * Applet.java
 *
 * Created on 24. Mai 2001, 18:28
 */


import Client.*;

/**
 *
 * @author
 * @version 
 */
public class Applet extends java.applet.Applet {

    private Client client;
        java.awt.CardLayout  card = new java.awt.CardLayout();

   
    /** Initializes the applet Applet */
    public void init () {
        initComponents ();
        this.client=new Client();
	
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainpanel = new java.awt.Panel();
        card1panel = new java.awt.Panel();
        password = new java.awt.TextField();
        name = new java.awt.TextField();
        guest = new java.awt.Checkbox();
        login = new java.awt.Button();
        card2panel = new java.awt.Panel();
        textArea1 = new java.awt.TextArea();
        textField5 = new java.awt.TextField();
        update = new java.awt.Button();
        send = new java.awt.Button();
        button6 = new java.awt.Button();
        setLayout(new java.awt.BorderLayout());
        mainpanel.setLayout(card);
        mainpanel.setFont(new java.awt.Font ("Dialog", 0, 11));
        mainpanel.setName("mainpanel");
        mainpanel.setBackground(new java.awt.Color (204, 204, 204));
        mainpanel.setForeground(java.awt.Color.black);
        
        card1panel.setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints1;
          card1panel.setFont(new java.awt.Font ("Dialog", 0, 11));
          card1panel.setName("card1panel");
          card1panel.setBackground(new java.awt.Color (153, 153, 153));
          card1panel.setForeground(java.awt.Color.black);
          
          password.setBackground(java.awt.Color.white);
            password.setName("textfield3");
            password.setFont(new java.awt.Font ("Dialog", 0, 11));
            password.setColumns(20);
            password.setForeground(java.awt.Color.black);
            gridBagConstraints1 = new java.awt.GridBagConstraints();
            gridBagConstraints1.gridx = 0;
            gridBagConstraints1.gridy = 1;
            card1panel.add(password, gridBagConstraints1);
            
            
          name.setBackground(java.awt.Color.white);
            name.setName("textfield4");
            name.setFont(new java.awt.Font ("Dialog", 0, 11));
            name.setColumns(20);
            name.setForeground(java.awt.Color.black);
            gridBagConstraints1 = new java.awt.GridBagConstraints();
            card1panel.add(name, gridBagConstraints1);
            
            
          guest.setBackground(new java.awt.Color (153, 153, 153));
            guest.setName("checkbox2");
            guest.setFont(new java.awt.Font ("Dialog", 0, 11));
            guest.setForeground(java.awt.Color.black);
            guest.setLabel("guest");
            guest.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    guestItemStateChanged(evt);
                }
            }
            );
            gridBagConstraints1 = new java.awt.GridBagConstraints();
            gridBagConstraints1.gridx = 1;
            gridBagConstraints1.gridy = 0;
            card1panel.add(guest, gridBagConstraints1);
            
            
          login.setFont(new java.awt.Font ("Dialog", 0, 11));
            login.setLabel("login");
            login.setName("button3");
            login.setBackground(java.awt.Color.lightGray);
            login.setForeground(java.awt.Color.black);
            login.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    loginMousePressed(evt);
                }
            }
            );
            gridBagConstraints1 = new java.awt.GridBagConstraints();
            gridBagConstraints1.gridx = 0;
            gridBagConstraints1.gridy = 2;
            card1panel.add(login, gridBagConstraints1);
            
            mainpanel.add(card1panel, "card1");
          
          
        card2panel.setLayout(new java.awt.GridBagLayout());
          java.awt.GridBagConstraints gridBagConstraints2;
          card2panel.setFont(new java.awt.Font ("Dialog", 0, 11));
          card2panel.setName("panel6");
          card2panel.setBackground(new java.awt.Color (153, 153, 153));
          card2panel.setForeground(java.awt.Color.black);
          
          textArea1.setBackground(java.awt.Color.white);
            textArea1.setFont(new java.awt.Font ("Dialog", 0, 11));
            textArea1.setColumns(50);
            textArea1.setEnabled(false);
            textArea1.setForeground(java.awt.Color.black);
            textArea1.setRows(20);
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            card2panel.add(textArea1, gridBagConstraints2);
            
            
          textField5.setBackground(java.awt.Color.white);
            textField5.setName("textfield5");
            textField5.setFont(new java.awt.Font ("Dialog", 0, 11));
            textField5.setColumns(50);
            textField5.setForeground(java.awt.Color.black);
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 0;
            gridBagConstraints2.gridy = 1;
            card2panel.add(textField5, gridBagConstraints2);
            
            
          update.setFont(new java.awt.Font ("Dialog", 0, 11));
            update.setLabel("update");
            update.setName("button4");
            update.setBackground(java.awt.Color.lightGray);
            update.setForeground(java.awt.Color.black);
            update.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    updateMousePressed(evt);
                }
            }
            );
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 1;
            gridBagConstraints2.gridy = 1;
            card2panel.add(update, gridBagConstraints2);
            
            
          send.setFont(new java.awt.Font ("Dialog", 0, 11));
            send.setLabel("send");
            send.setName("button5");
            send.setBackground(java.awt.Color.lightGray);
            send.setForeground(java.awt.Color.black);
            send.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    sendMousePressed(evt);
                }
            }
            );
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 0;
            gridBagConstraints2.gridy = 2;
            card2panel.add(send, gridBagConstraints2);
            
            
          button6.setFont(new java.awt.Font ("Dialog", 0, 11));
            button6.setLabel("button6");
            button6.setName("button6");
            button6.setBackground(java.awt.Color.lightGray);
            button6.setForeground(java.awt.Color.black);
            gridBagConstraints2 = new java.awt.GridBagConstraints();
            gridBagConstraints2.gridx = 1;
            gridBagConstraints2.gridy = 2;
            card2panel.add(button6, gridBagConstraints2);
            
            mainpanel.add(card2panel, "card2");
          
          
        add(mainpanel, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

  private void guestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_guestItemStateChanged
// Add your handling code here:
  }//GEN-LAST:event_guestItemStateChanged

  private void updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMousePressed
    this.textArea1.setText(this.client.channelMsgBuffer);
  }//GEN-LAST:event_updateMousePressed

  private void sendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMousePressed
    this.client.sendMsgToChannel(this.textField5.getText());
  }//GEN-LAST:event_sendMousePressed

  private void loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMousePressed
// Add your handling code here:
    this.client.startClient();
    if(this.guest.getState()){
     this.client.loginAsGuest(this.name.getText());

    }
    else{
     this.client.login(this.name.getText(),this.password.getText());
    }
    this.card.next(this.mainpanel);

  }//GEN-LAST:event_loginMousePressed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Panel mainpanel;
  private java.awt.Panel card1panel;
  private java.awt.TextField password;
  private java.awt.TextField name;
  private java.awt.Checkbox guest;
  private java.awt.Button login;
  private java.awt.Panel card2panel;
  private java.awt.TextArea textArea1;
  private java.awt.TextField textField5;
  private java.awt.Button update;
  private java.awt.Button send;
  private java.awt.Button button6;
  // End of variables declaration//GEN-END:variables

}
