/* Generated by Together */

package Util.Commands;

import Client.Client;

/**
* Wird von einem ClientServant gesendet, falls ein joinChannel() Aufruf
* fehlschlägt.
*/

public class JoinChannelErrorCommand implements Command {
    /**Führt beim Client joinChannelError() auf.*/
    public void execute(Object target) {
        if (target instanceof Client) {
            ((Client)target).joinChannelError();
        } // XXX: else Exception auslösen?
    }
}
