/* Generated by Together */

package Client;
import java.net.Socket;


/**
 * empfängt Daten vom Server 
 */
public class Downlink extends Thread{
    public Downlink(Socket socket) {
    }

    /**
     * wartet auf ankommende Daten und leitet diese an den Client weiter 
     */
    private void listen() {
      this.client.processMsg("Mensachat, Virtuelle Konferenz, tubs intern");
    }

    /**
     * startet den Stream 
     */
    public void startDownlink() {
    }

    /**
     * schließt den Stream 
     */
    public void stopDownlink() {
    }
    
    /**
    * Methode für den Thread
    */
    public void run() {
      listen();
    }
    
    /**
    *togetherJ dummy
    */
    
    public void start() {
      run();
    }

    /**
     * @directed
     * @supplierCardinality 1
     * @clientCardinality 1 
     */
    private Client client;
    private Socket socket;
}
