/* Generated by Together */

package Client;
import java.net.Socket;


/**
 * Empfängt Daten vom Server
 */
public class Downlink extends Thread{
    public Downlink(Socket socket) {
    }

    /**
     * Wartet auf ankommende Daten und leitet diese an den Client weiter.
     */
    private void listen() {
      this.client.processMsg("Mensachat, Virtuelle Konferenz, tubs intern");
    }

    /**
     * Startet den Input - Stream 
     */
    public void startDownlink() {
    }

    /**
     * Schließt den Input - Stream 
     */
    public void stopDownlink() {
    }
    
    /**
    * Methode für den Thread
    */
    public void run() {
      listen();
    }
    
    /**
    *togetherJ dummy
    */
    
    public void start() {
      run();
    }

    /**
     * @directed
     * @supplierCardinality 1
     * @clientCardinality 1 
     */
    private Client client;
    private Socket socket;
}
