/* Generated by Together */

package Client;
import java.net.Socket;

/**
 * Sendet Daten an den Server.
 */
public class Uplink {
    public Uplink(Socket socket) {
    }

    private Socket socket;

    /**
     * Startet den Output - Stream
     */
    public void startUplink() {
    }

    /**
     * Schließt den Output - Stream 
     */
    public void stopUplink() {
    }

    /**
     * Sendet eine Nachricht an den Server.
     */
    public void sendMsg(String msg) {
    }
}
