/* Generated by Together */

package Client;
import java.net.Socket;

/**
 * sendet Daten an den Server 
 */
public class Uplink {
    public Uplink(Socket socket) {
    }

    private Socket socket;

    /**
     * startet den Stream 
     */
    public void startUplink() {
    }

    /**
     * schließt den Stream 
     */
    public void stopUplink() {
    }

    /**
     * sendet eine Nachricht an den Server 
     */
    public void sendMsg(String msg) {
    }
}
