/*
 * ChannelAdminGUI.java
 *
 * Created on May 24, 2001, 9:32 PM
 */


/**
 *
 * @author  andreas
 * @version 
 */
public class ChannelAdminGUI extends java.applet.Applet {

    /** Initializes the applet ChannelAdminGUI */
    public void init () {
        initComponents ();
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        list1 = new java.awt.List();
        button1 = new java.awt.Button();
        button3 = new java.awt.Button();
        button2 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        label4 = new java.awt.Label();
        list2 = new java.awt.List();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        label3 = new java.awt.Label();
        list3 = new java.awt.List();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        label1.setFont(new java.awt.Font ("Dialog", 0, 11));
        label1.setName("channelNameLabel");
        label1.setBackground(new java.awt.Color (204, 204, 204));
        label1.setForeground(java.awt.Color.black);
        label1.setText("Channelname");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 15);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        add(label1, gridBagConstraints1);
        
        
        textField1.setBackground(java.awt.Color.white);
        textField1.setName("channelNameField");
        textField1.setFont(new java.awt.Font ("Dialog", 0, 11));
        textField1.setForeground(new java.awt.Color (0, 0, 0));
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        add(textField1, gridBagConstraints1);
        
        
        label2.setFont(new java.awt.Font ("Dialog", 0, 11));
        label2.setName("channelListLabel");
        label2.setBackground(new java.awt.Color (204, 204, 204));
        label2.setForeground(java.awt.Color.black);
        label2.setText("Channelliste");
        label2.setAlignment(java.awt.Label.CENTER);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.gridwidth = 12;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 10);
        add(label2, gridBagConstraints1);
        
        
        list1.setFont(new java.awt.Font ("Dialog", 0, 11));
        list1.setName("channelList");
        list1.setBackground(java.awt.Color.white);
        list1.setForeground(new java.awt.Color (0, 0, 0));
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 12;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 10);
        gridBagConstraints1.weightx = 1.0;
        add(list1, gridBagConstraints1);
        
        
        button1.setFont(new java.awt.Font ("Dialog", 0, 11));
        button1.setLabel("Bearbeiten");
        button1.setName("editChannelButton");
        button1.setBackground(new java.awt.Color (204, 204, 204));
        button1.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = 12;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 10);
        add(button1, gridBagConstraints1);
        
        
        button3.setFont(new java.awt.Font ("Dialog", 0, 11));
        button3.setLabel("Neu");
        button3.setName("newChannelButton");
        button3.setBackground(new java.awt.Color (204, 204, 204));
        button3.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 10, 15, 0);
        gridBagConstraints1.weightx = 1.0;
        add(button3, gridBagConstraints1);
        
        
        button2.setFont(new java.awt.Font ("Dialog", 0, 11));
        button2.setLabel("Kopieren");
        button2.setName("copyChannelButton");
        button2.setBackground(new java.awt.Color (204, 204, 204));
        button2.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = 12;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 15, 10);
        add(button2, gridBagConstraints1);
        
        
        button4.setFont(new java.awt.Font ("Dialog", 0, 11));
        button4.setLabel("Speichern");
        button4.setName("saveChannelButton");
        button4.setBackground(new java.awt.Color (204, 204, 204));
        button4.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 0, 15, 0);
        gridBagConstraints1.weightx = 1.0;
        add(button4, gridBagConstraints1);
        
        
        button5.setFont(new java.awt.Font ("Dialog", 0, 11));
        button5.setLabel("L\u00f6schen");
        button5.setName("deleteChannelButton");
        button5.setBackground(new java.awt.Color (204, 204, 204));
        button5.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 8;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 0, 15, 10);
        gridBagConstraints1.weightx = 1.0;
        add(button5, gridBagConstraints1);
        
        
        label4.setFont(new java.awt.Font ("Dialog", 0, 11));
        label4.setName("passiveUsersLabel");
        label4.setBackground(new java.awt.Color (204, 204, 204));
        label4.setForeground(java.awt.Color.black);
        label4.setText("Nicht berechtigte User");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(15, 10, 0, 0);
        add(label4, gridBagConstraints1);
        
        
        list2.setFont(new java.awt.Font ("Dialog", 0, 11));
        list2.setMultipleMode(true);
        list2.setName("passiveUsersList");
        list2.setBackground(java.awt.Color.white);
        list2.setForeground(new java.awt.Color (0, 0, 0));
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.gridheight = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 10, 0);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(list2, gridBagConstraints1);
        
        
        button6.setFont(new java.awt.Font ("Dialog", 0, 11));
        button6.setLabel(">>>");
        button6.setName("addToChannelButton");
        button6.setBackground(new java.awt.Color (204, 204, 204));
        button6.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 5;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 2;
        gridBagConstraints1.insets = new java.awt.Insets(10, 15, 10, 15);
        add(button6, gridBagConstraints1);
        
        
        button7.setFont(new java.awt.Font ("Dialog", 0, 11));
        button7.setLabel("<<<");
        button7.setName("removeFromChannelButton");
        button7.setBackground(new java.awt.Color (204, 204, 204));
        button7.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 5;
        gridBagConstraints1.gridy = 8;
        gridBagConstraints1.gridwidth = 2;
        gridBagConstraints1.insets = new java.awt.Insets(10, 15, 10, 15);
        add(button7, gridBagConstraints1);
        
        
        label3.setFont(new java.awt.Font ("Dialog", 0, 11));
        label3.setName("activeUsersLabel");
        label3.setBackground(new java.awt.Color (204, 204, 204));
        label3.setForeground(java.awt.Color.black);
        label3.setText("Berechtigte User");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(15, 0, 0, 10);
        add(label3, gridBagConstraints1);
        
        
        list3.setFont(new java.awt.Font ("Dialog", 0, 11));
        list3.setMultipleMode(true);
        list3.setName("activeUsersList");
        list3.setBackground(java.awt.Color.white);
        list3.setForeground(new java.awt.Color (0, 0, 0));
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.gridheight = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 10, 10);
        gridBagConstraints1.weightx = 1.0;
        gridBagConstraints1.weighty = 1.0;
        add(list3, gridBagConstraints1);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.TextField textField1;
    private java.awt.Label label2;
    private java.awt.List list1;
    private java.awt.Button button1;
    private java.awt.Button button3;
    private java.awt.Button button2;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Label label4;
    private java.awt.List list2;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Label label3;
    private java.awt.List list3;
    // End of variables declaration//GEN-END:variables

}
