/*
 * UserAdminGUI.java
 *
 * Created on May 24, 2001, 1:44 PM
 */


/**
 *
 * @author  andreas
 * @version 
 */
public class UserAdminGUI extends java.applet.Applet {

    /** Initializes the applet UserAdminGUI */
    public void init () {
        initComponents ();
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        label2 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label3 = new java.awt.Label();
        label1 = new java.awt.Label();
        list1 = new java.awt.List();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        checkbox2 = new java.awt.Checkbox();
        label4 = new java.awt.Label();
        list3 = new java.awt.List();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        list2 = new java.awt.List();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        label2.setFont(new java.awt.Font ("Dialog", 0, 11));
        label2.setName("passwordLabel");
        label2.setBackground(new java.awt.Color (204, 204, 204));
        label2.setForeground(java.awt.Color.black);
        label2.setText("Passwort");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = 3;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        add(label2, gridBagConstraints1);
        
        
        textField1.setBackground(java.awt.Color.white);
        textField1.setName("loginField");
        textField1.setFont(new java.awt.Font ("Dialog", 0, 11));
        textField1.setForeground(java.awt.Color.black);
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        }
        );
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(textField1, gridBagConstraints1);
        
        
        label3.setFont(new java.awt.Font ("Dialog", 0, 11));
        label3.setName("passwordVerifyLabel");
        label3.setBackground(new java.awt.Color (204, 204, 204));
        label3.setForeground(java.awt.Color.black);
        label3.setText("Wiederholung");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = 3;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        add(label3, gridBagConstraints1);
        
        
        label1.setFont(new java.awt.Font ("Dialog", 0, 11));
        label1.setName("loginLabel");
        label1.setBackground(new java.awt.Color (204, 204, 204));
        label1.setForeground(java.awt.Color.black);
        label1.setText("Login Name");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 3;
        gridBagConstraints1.insets = new java.awt.Insets(1, 0, 0, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.EAST;
        add(label1, gridBagConstraints1);
        
        
        list1.setFont(new java.awt.Font ("Dialog", 0, 11));
        list1.setName("userList");
        list1.setBackground(java.awt.Color.white);
        list1.setForeground(java.awt.Color.black);
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        }
        );
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.gridheight = 11;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.ipadx = 3;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 30);
        gridBagConstraints1.weightx = 0.5;
        gridBagConstraints1.weighty = 1.0;
        add(list1, gridBagConstraints1);
        
        
        textField3.setBackground(java.awt.Color.white);
        textField3.setName("passwordField");
        textField3.setFont(new java.awt.Font ("Dialog", 0, 11));
        textField3.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(textField3, gridBagConstraints1);
        
        
        textField4.setBackground(java.awt.Color.white);
        textField4.setName("passwordVerifyField");
        textField4.setFont(new java.awt.Font ("Dialog", 0, 11));
        textField4.setForeground(java.awt.Color.black);
        textField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField4ActionPerformed(evt);
            }
        }
        );
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(textField4, gridBagConstraints1);
        
        
        checkbox2.setBackground(new java.awt.Color (204, 204, 204));
        checkbox2.setName("isAdminCheckbox");
        checkbox2.setFont(new java.awt.Font ("Dialog", 0, 11));
        checkbox2.setForeground(java.awt.Color.black);
        checkbox2.setLabel(" ist Admin");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 7;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.gridwidth = 8;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 10);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        add(checkbox2, gridBagConstraints1);
        
        
        label4.setFont(new java.awt.Font ("Dialog", 0, 11));
        label4.setName("userListLabel");
        label4.setBackground(new java.awt.Color (204, 204, 204));
        label4.setForeground(java.awt.Color.black);
        label4.setText("Userliste");
        label4.setAlignment(java.awt.Label.CENTER);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 30);
        add(label4, gridBagConstraints1);
        
        
        list3.setFont(new java.awt.Font ("Dialog", 0, 11));
        list3.setMultipleMode(true);
        list3.setName("passiveChannelList");
        list3.setBackground(java.awt.Color.white);
        list3.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.gridheight = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 10, 15);
        gridBagConstraints1.weightx = 1.0;
        add(list3, gridBagConstraints1);
        
        
        button1.setFont(new java.awt.Font ("Dialog", 0, 11));
        button1.setLabel(">>>");
        button1.setName("addToChannels");
        button1.setBackground(new java.awt.Color (204, 204, 204));
        button1.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 9;
        gridBagConstraints1.gridy = 9;
        add(button1, gridBagConstraints1);
        
        
        button2.setFont(new java.awt.Font ("Dialog", 0, 11));
        button2.setLabel("<<<");
        button2.setName("removeFromChannels");
        button2.setBackground(new java.awt.Color (204, 204, 204));
        button2.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 9;
        gridBagConstraints1.gridy = 11;
        add(button2, gridBagConstraints1);
        
        
        list2.setFont(new java.awt.Font ("Dialog", 0, 11));
        list2.setMultipleMode(true);
        list2.setName("activeChannelList");
        list2.setBackground(java.awt.Color.white);
        list2.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 10;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.gridheight = 8;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.insets = new java.awt.Insets(0, 15, 10, 10);
        gridBagConstraints1.weightx = 1.0;
        add(list2, gridBagConstraints1);
        
        
        label5.setFont(new java.awt.Font ("Dialog", 0, 11));
        label5.setName("passiveChannelListField");
        label5.setBackground(new java.awt.Color (204, 204, 204));
        label5.setForeground(java.awt.Color.black);
        label5.setText("Inaktive Channels");
        label5.setAlignment(java.awt.Label.CENTER);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 4;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.insets = new java.awt.Insets(15, 0, 0, 10);
        add(label5, gridBagConstraints1);
        
        
        label6.setFont(new java.awt.Font ("Dialog", 0, 11));
        label6.setName("activeChannelListField");
        label6.setBackground(new java.awt.Color (204, 204, 204));
        label6.setForeground(java.awt.Color.black);
        label6.setText("Aktive Channels");
        label6.setAlignment(java.awt.Label.CENTER);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 10;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.insets = new java.awt.Insets(15, 0, 0, 10);
        add(label6, gridBagConstraints1);
        
        
        button3.setFont(new java.awt.Font ("Dialog", 0, 11));
        button3.setLabel("Bearbeiten");
        button3.setName("editUser");
        button3.setBackground(new java.awt.Color (204, 204, 204));
        button3.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 13;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 0, 30);
        add(button3, gridBagConstraints1);
        
        
        button4.setFont(new java.awt.Font ("Dialog", 0, 11));
        button4.setLabel("Kopieren");
        button4.setName("copyUserData");
        button4.setBackground(new java.awt.Color (204, 204, 204));
        button4.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 14;
        gridBagConstraints1.gridwidth = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(0, 10, 10, 30);
        add(button4, gridBagConstraints1);
        
        
        button5.setFont(new java.awt.Font ("Dialog", 0, 11));
        button5.setLabel("Neu");
        button5.setName("newUser");
        button5.setBackground(new java.awt.Color (204, 204, 204));
        button5.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 10, 15, 0);
        gridBagConstraints1.weightx = 1.0;
        add(button5, gridBagConstraints1);
        
        
        button6.setFont(new java.awt.Font ("Dialog", 0, 11));
        button6.setLabel("Speichern");
        button6.setName("saveUser");
        button6.setBackground(new java.awt.Color (204, 204, 204));
        button6.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 5;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 0, 15, 0);
        gridBagConstraints1.weightx = 1.0;
        add(button6, gridBagConstraints1);
        
        
        button7.setFont(new java.awt.Font ("Dialog", 0, 11));
        button7.setLabel("L\u00f6schen");
        button7.setName("deleteUser");
        button7.setBackground(new java.awt.Color (204, 204, 204));
        button7.setForeground(java.awt.Color.black);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 10;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(10, 0, 15, 10);
        gridBagConstraints1.weightx = 1.0;
        add(button7, gridBagConstraints1);
        
    }//GEN-END:initComponents

  private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_list1ActionPerformed

  private void textField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField4ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_textField4ActionPerformed

  private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_textField1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Label label2;
  private java.awt.TextField textField1;
  private java.awt.Label label3;
  private java.awt.Label label1;
  private java.awt.List list1;
  private java.awt.TextField textField3;
  private java.awt.TextField textField4;
  private java.awt.Checkbox checkbox2;
  private java.awt.Label label4;
  private java.awt.List list3;
  private java.awt.Button button1;
  private java.awt.Button button2;
  private java.awt.List list2;
  private java.awt.Label label5;
  private java.awt.Label label6;
  private java.awt.Button button3;
  private java.awt.Button button4;
  private java.awt.Button button5;
  private java.awt.Button button6;
  private java.awt.Button button7;
  // End of variables declaration//GEN-END:variables

}
