/* Generated by Together */

package Server;

import java.util.Vector;
/**
 * verwaltet die Channel 
 */
class ChannelAdministration {
    public ChannelAdministration(DataBaseIO paramDataBaseIO) {
    }

    /**
     * gibt den Channel mit dem angegebenen Namen zurück 
     */
    public Channel getByName(String name) {
        return null;
    }

    /**
     * fügt einen Channel hinzu 
     */
    public void addToChannelList(Channel paramChannel) {
    }

    /**
     * entfernt einen Channel 
     */
    public void removeFromChannelList(Channel paramChannel) {
     int pos=0;
     User tmpUser=(User)(paramChannel.getCurrentUserList().elementAt(pos));
     tmpUser.getClientServant().leaveChannel();
    }

    public void setChannelList(java.util.Vector channelList){
        this.channelList = channelList;
    }

    public java.util.Vector getChannelList(){
        return channelList;
    }

    /**
     * editiert den Channel mit dem angegebenen Namen mit einem neuen Datensatz aus einem String
     */
    public void editChannel(String name, String newChannelData) {

     
    }

    /**
     *@link aggregation
     *     @associates <{Channel}>
     * @clientCardinality 1
     * @supplierCardinality 0..*
     */
    private Vector channelList;

    /**
     * @supplierCardinality 1
     * @clientCardinality 1 
     */
    private DataBaseIO dataBaseIO;
}
