/* Generated by Together */

package Server;

import java.util.Vector;

 
/**
 * ein Channeldatensatz:
 * Eine Instanz dieser Klasse kann wichtige Channeldaten wie z.B.
 * berechtigte User oder im Channel befindliche User speichern.
 * Außerdem stehen Methoden zur Verfügung, mit denen Listen der berechtigten
 * bzw. im Raum befindlichen User abgefragt und übergeben werden können.
 * Desweiteren können einzelne User zu den CurrentUser hinzugefügt bzw.
 * wieder entfernt werden, wenn sie den Channel betreten bzw. verlassen.
 */
 
class Channel {
    public Channel(String channelSet) {
    }
    /**
    *  liefert alle sich zu dieser Zeit im Channel aufhaltenden User
    */

    public Vector getCurrentUserList(){
            return currentUserList;
        }
	
     /**
    *    setzt die sich im Channel aufhaltenden User
    */
	

    public void setCurrentUserList(Vector currentUserList){
            this.currentUserList = currentUserList;
        }

    /**
    *   fügt einen User zu den im Channel befindlichen Usern hinzu
    */


    public void addToCurrentUserList(User paramUser) {
     int pos=0;
     this.currentUserList.add(paramUser);
     User tmpUser=(User)(this.currentUserList.elementAt(pos));
     ClientServant tmpClientServant=tmpUser.getClientServant();
     tmpClientServant.sendChannelData();
    }

    /**
    *   entfernt einen User von den im Channel befindlichen Usern
    */


    public void removeFromCurrentUserList(User paramUser) {
     int pos=0;
     this.currentUserList.remove(paramUser);
     User tmpUser=(User)(this.currentUserList.elementAt(pos));
     ClientServant tmpClientServant=tmpUser.getClientServant();
     tmpClientServant.sendChannelData();
    }

    /**
    *   Gibt eine Liste aller berechtigten User für diesen Channel zurück
    */


    public Vector getAllowedUserList(){
            return allowedUserList;
        }

    /**
    *   setzt die berechtigten User für diesen Channel
    */


    public void setAllowedUser(Vector allowedUser){
            this.allowedUserList = allowedUserList;
        }

    /** gibt die Benutzer an, die sich momentan in dem Channel befinden
     * @associates <{User}>
     * @supplierCardinality 0..*
     * @clientCardinality 0..1
     * @supplierRole currentUser
     * @clientRole currentChannel
     * @label current state*/
    private Vector currentUserList;

    /** gibt die Benutzer an, die den Channel betreten dürfen
     * @associates <{User}>
     * @clientCardinality 0..*
     * @supplierCardinality 0..*
     * @supplierRole allowedUser
     * @clientRole allowedChannel
     * @label allowance relation*/
    private Vector allowedUserList;

    /**
     * gibt an, ob der Datensatz seit dem letzten Laden verändert wurde - wird von DataBaseIO benötigt 
     */
    private boolean modified;

    /**
     * @supplierCardinality 0..*
     * @clientCardinality 0..* 
     */
    private ChannelAdministration channelAdministration;
}
