/* Generated by Together */

package Server;
import java.util.Vector;

/**
 * stellt Methoden bereit, um die Benutzer- und Channeldatenbank zu laden
 * und zu speichern. Außerdem wird dafür gesorgt, daß für den Betrieb die
 * Beziehungen zwischen User- und Channeldatenbank gesetzt werden
 */

class DataBaseIO {
         /**
     * lädt die Benutzer- und Channeldaten aus userDBFile und channelDBFile
     */

    public void loadFromDisk() {
     Vector tmpVector=new Vector();
     Vector tmp2Vector=new Vector();
     this.userAdministration.setUserList(tmpVector);
     this.channelAdministration.setChannelList(tmpVector);
     doLinks();
    }

    /**
     * speichert die Benutzer- und Channeldaten in userDBFile und channelDBFile
     */

    public void saveToDisk() {

    }

    /**
     * stellt die relationalen Beziehungen zwische User- und Channeldatensätzen her 
     */
    private void doLinks() {
     int pos=0;
     Channel tmpChannel=(Channel)(this.channelAdministration.getChannelList().elementAt(pos));
     User tmpUser=(User)(this.userAdministration.getUserList().elementAt(pos));
     tmpChannel.setAllowedUser(new Vector());
     tmpUser.setAllowedChannel(new Vector());

    }

    /**
     * @clientCardinality 1
     * @supplierCardinality 1 
     */
    private UserAdministration userAdministration;

    /**
     * @clientCardinality 1
     * @supplierCardinality 1 
     */
    private ChannelAdministration channelAdministration;

    /**
     * Dateiname der Channeldatenbank 
     */
    private final static String channelDBFile = "channel.db";

    /**
     * Dateiname der Benutzerdatenbank 
     */
    private final static String userDBFile = "user.db";
}
