/* Generated by Together */

package Server;
import java.net.Socket;

/**
 * empfängt Nachrichten von der Clientapplikation und leitet diese an den Observer weiter 
 */
class Downlink extends Thread {
    public Downlink(Socket paramSocket, ClientServant paramClientServant) {
    }

    /**
     * wartet auf ankommende Nachrichten und leitet diese an den ClientServant weiter 
     */
    public void listen() {
     String msg="foo";
     this.ClientServant.processMsg("login UserFoo");
     listen();


    }

    /**
     * öffnet den Stream, danach ist der Downlink betriebsbereit 
     */
    public void startDownlink() {
    }

    public void run(){
     this.listen();
    }

    /**
     * schließt den Stream 
     */
    public void stopDownlink() {
    }

    public ClientServant getClientServant(){
            return this.ClientServant;
        }

    public void setClientServant(ClientServant ClientServant){
            this.ClientServant = ClientServant;
        }

    public void start() {
      run();
    }

    /**
     * @supplierCardinality 1
     * @clientCardinality 1 
     */
    private ClientServant ClientServant;
}
