/* Generated by Together */

package Server;
import java.net.Socket;

/**
 * Empfängt Nachrichten von der Clientapplikation und leitet diese an den (Admin)ClientServant weiter.
 */
class Downlink extends Thread {
    public Downlink(Socket paramSocket, ClientServant paramClientServant) {
    }

    /**
     * Wartet auf ankommende Nachrichten und leitet diese an den ClientServant weiter.
     */
    public void listen() {
     String msg="foo";
     this.ClientServant.processMsg("login UserFoo");
     listen();


    }

    /**
     * Öffnet den Input - Stream, danach ist der Downlink betriebsbereit.
     */
    public void startDownlink() {
    }

    public void run(){
     this.listen();
    }

    /**
     * Schließt den Input - Stream 
     */
    public void stopDownlink() {
    }

    public ClientServant getClientServant(){
            return this.ClientServant;
        }

    public void setClientServant(ClientServant ClientServant){
            this.ClientServant = ClientServant;
        }

    public void start() {
      run();
    }

    /**
     * @supplierCardinality 1
     * @clientCardinality 1 
     */
    private ClientServant ClientServant;
}
