/* Generated by Together */

package Server;
import java.net.Socket;

/**
 * ermöglicht dem Observer das Senden von Nachrichten an die Clientapplikation 
 */
class Uplink {
    public Uplink(Socket paramSocket) {
    }

    /**
     * sendet eine Nachricht zur Clientapplikation 
     */
    public void send(String msg) {
    }

    /**
     * startet den Stream, danach ist Uplink betriebsbereit 
     */
    public void startUplink() {
    }

    /**
     * schließt den Stream 
     */
    public void stopUplink() {
    }
}
