/* Generated by Together */

package Server;
import java.net.Socket;

/**
 * Ermöglicht dem Observer das Senden von Nachrichten an die Clientapplikation.
 */
class Uplink {
    public Uplink(Socket paramSocket) {
    }

    /**
     * Sendet eine Nachricht zur Clientapplikation.
     */
    public void send(String msg) {
    }

    /**
     * Startet den Output - Stream, danach ist der Uplink betriebsbereit.
     */
    public void startUplink() {
    }

    /**
     * Schließt den Output - Stream.
     */
    public void stopUplink() {
    }
}
